### PR TITLE
Change the salt_verbose setting to true by default

### PR DESCRIPTION
**Pull request by rick-nu**
### What

Personally, I think the `salt_verbose` should be `true` by default. For larger projects (especially one with zend server), you would be staring at one line stating your box is installing, for a quite a while. Now you can at least see what's going on.

This is personal preference, so feel free to shoot this down. But maybe more people think the same way about this :)

### CODE REVIEW

**Comment by jvandijk** [comment]
My advice... keep it false in the Vagrantfile, keep the true value commented in the local.dist file.
Because of the fact that in almost every case you are required to create the local file because of the IP change, I think that is sufficient.

**Comment by rick-nu** [comment]
Fair enough, this will take away most of my annoyance too :smile:

**Comment by eXistenZNL** [comment]
The Vagrantfile.local.dist reflects the exact options set in the Vagrantfile, so everyone can what the default setting and thus behaviour is by simply looking at the commented out option in the Vagrantfile.local.dist. This change breaks that behaviour and thus I would not +1ing this.

Also, it takes 5 seconds per project to configure this, so why changing the dist file at all?
Isn't the Vagrantfile.local file for this exact purpose to begin with?

**Comment by eXistenZNL** [comment]
To be clear: I would +1 this if you also set verbose to true in the Vagrantfile itself since that should match with the Vagrantfile.local.dist. I don't care since what goes for you also goes for me; it's just 5 seconds to disable verbose output so if I don't like it I will simply disable it.

**Comment by rick-nu** [comment]
@eXistenZNL updated

**Comment by eXistenZNL** [comment]
:+1: from me, @syphernl plz merge if you agree with it.

**Pull request merged**
