### PR TITLE
NFS mount options should be respected for all mounts

### PR DESCRIPTION
**Pull request by renatomefi**
Custom nfs mount options are not being respect on basebox and salt paths

### CODE REVIEW

**Review by nstapelbroek — APPROVED** [review]

**Comment by nstapelbroek** [comment]
I noticed there are some other mount options present in the file. Might be worth adding these statements for those as well?

**Comment by renatomefi** [comment]
@nstapelbroek I did it for the remaining NFS mount, won't do it for the other mount types since I can't test and it's another context

**Comment by nstapelbroek** [comment]
@renatomefi great, I'll ping @eXistenZNL to check the changes. Else I'm merging it

**Comment by syphernl** [comment]
You might want to verify the settings. Before it had a few hardcoded options (`'rw', 'vers=3', 'tcp', 'nolock'`) and now it only would have `activemo=2`. 

Wouldn't these hardcoded options be merged with the default declaration of [$mount_options_nfs](https://github.com/renatomefi/Basebox/blob/2fdcba8430917a474497781595a167f0300deb8b/Vagrantfile#L11)?

**Comment by eXistenZNL** [comment]
@renatomefi Looking sharp bro! Thanks for the improvement.

@syphernl I don't feel we need the settings at all. actimeo=2 is working on Ubuntu out of the box which sets a lot of random other properties (actimeo is really strange, see the docs), and on Fedora this can be manually changed to whatever Fedora needs to work like a proper OS.

The main thing here is that all mounts will work the same, which makes really good sense to me :)

**Comment by nstapelbroek** [comment]
I'll push a proposal for updating the default arguments

**Comment by nstapelbroek** [comment]
Patched the Default arguments with the settings we are shipping in https://github.com/Enrise/Basebox/blob/master/Vagrantfile.local.dist

Lets merge?

**Review by syphernl — APPROVED** [review]

**Comment by eXistenZNL** [comment]
@jvandijk After some discussion with @nstapelbroek about the NFS options that should go in the Vagrantfile by default, it turns out that Nico applied the NFS options that are stored in Vagrantfile.local.dist so that the Vagrantfile is in sync again. This was already the idea since I synced the options in Vagrantfile with Vagrantfile.local.dist so a developer can open their .local file and quickly see what the default settings are if they leave a setting disabled.

It turns out that we got out of alignment between the Vagrantfile and the .local file by this push to master:

https://github.com/Enrise/Basebox/commit/1f3aa3f55bb47e9f0fa10c1476416254b4dcccf0

I find this strange, because:
1) It seems that this is not a PR but a straight push to master
2) This breaks the idea to have Vagrantfile and Vagrantfile.local in sync regarding default options.

Please elaborate \o/

**Review by eXistenZNL — COMMENTED** [review]
Awaiting feedback from @jvandijk

**Comment by jvandijk** [comment]
I can remember this discussion, I can't remember though why this wasn't applied to the main Vagrantfile

**Comment by nstapelbroek** [comment]
I think we can add an improvement about what arguments we want to set as a default. But it should not block merging this.

**Comment by eXistenZNL** [comment]
Oh well, merged. It's a great improvment either way.

**Pull request merged**
