### PR TITLE
Improved the update checker

### PR DESCRIPTION
**Pull request by eXistenZNL**

### CODE REVIEW

**Comment by syphernl** [comment]
Nice! :+1:

**Comment by jvandijk** [comment]
@Enrise/servicedesk what's the value of a PR template when you are not using it?

**Comment by eXistenZNL** [comment]
@Enrise/sashimi what PR template are you referring to?

**Comment by jvandijk** [comment]
@eXistenZNL my bad.... I was thinking this was the Saltmaster

**Comment by eXistenZNL** [comment]
@jvandijk no problem. It might be a good idea to add one though! Will discuss with @syphernl :)

**Pull request merged**
